---
title: "index"
author: "Shirel"
date: "November 30, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## scatterplot


```{r scatterplot}
summary(cars)

mpg

g <- ggplot(data = mpg, aes(x=displ, y=hwy))

g + geom_point()
```
### I need colour

```{r colour}
g <- ggplot(data = mpg, aes(x=displ, y=hwy, color = class))+ 
  geom_point()
g
```

## bw figure
```{r bw}
g <- ggplot(data = mpg, aes(x=displ, y=hwy, shape = class))+ 
  geom_point()
g
```

## size figure
```{r size}
g <- ggplot(data = mpg, aes(x=displ, y=hwy, size = class))+ 
  geom_point()
g
```

## fix colour figure
```{r fix colour}
g <- ggplot(data = mpg, aes(x=displ, y=hwy, size = class))+ 
  geom_point(alpha = 0.2, color = "blue")
g
```

## exercise figure
```{r exercise}
ggplot(data = mpg, aes(x=displ, y=hwy, color = cty))+ geom_point()
g
```
### violin
```{r geom_examples}
ggplot(data=mpg, aes(x=drv, y=hwy)) +
  geom_violin()
```
###multi
```{r geom_multi}
ggplot(data=mpg)+
  geom_point(aes(x=displ,y=hwy))+
  geom_smooth(aes(x=displ, y=hwy))
```
### customize 
```{r custom}
ggplot(data=mpg, aes(x=displ,y=hwy))+
  geom_point()+
  geom_smooth()+
  labs(title = "relationship b/w engine size and MPG", x= "Highway MPG", y="Engine displacement")+
  theme_bw()+
  theme(text = element_text(size = 16))
```

```{r gapminder}
gapminder <- readr::read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")

gapminder

## useful functions to get to know your data

head(gapminder)
tail(gapminder)
head(gapminder, 30)
tail(gapminder, 9)

str(gapminder)
names(gapminder)
dim(gapminder)
ncol(gapminder)
nrow(gapminder)

c(nrow(gapminder), ncol(gapminder))
summary(gapminder)

#everything above was done on the whole gapminder data set

head(gapminder$lifeExp) 
```

### Using dplyr
```{r dplyr}
filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
lifeExpSweden <- filter(gapminder, country == "Sweden")

## pipe operator '%>%'
gapminder %>% head()

#same output, pipe for sweden
gapminder %>%
  filter(country == "Sweden") %>%
  summarise(mean(lifeExp))


#read_csv from the readr package of the tinyverse, it's not the read.csv which is part of base r
